name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: server_config

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd docker/discord_chatbot
            git pull origin main

            docker stop discord_chatbot || true
            docker rm discord_chatbot || true
            docker rmi discord_chatbot || true

            docker build -t discord_chatbot .
            docker run -d --restart=always -v discord_chatbot:/app/storage --name discord_chatbot discord_chatbot